### ISSUE TITLE
Missing script: start

### ISSUE THREAD

**Issue by robomantis19** [AnthoniG/puppeteer-electron#1]
2019-08-09T04_17_47_219Z-debug.log
what am I missing

**Comment by AnthoniG** [comment]
Wow, am really sorry I never got notified for this :disappointed: 
Did you fix the problem?

Also as a note, you've shown the name of the log file, but not attached it :wink:

**Comment by AnthoniG** [comment]
Not heard back in a while so I will presume you fixed it.
However if not, please feel free to re-open it and I will do my best to help.
